services:
  # Patient DB Service
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    ports:
      - "5000:5432"
    volumes:
      - ./db_volumes/patient-service-db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
    networks:
      - internal_net

  # Patient Application Service
  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge
    # internal: true  # Commented out to work in local using external dev tools, uncomment during higher env movement
